version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - aws s3 rm --recursive "arn:aws:s3:::alexmiller-software.com"
      - npm run build
artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: 'dist*'