version: 0.2

phases:
  pre_build:
    commands:
      - npm install
      - aws s3 rm --recursive $ARTIFACTS_BUCKET
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: 'dist*'